dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: go-jx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: node-http-demo1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: node-jx1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: node-quest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: node-test-jx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
